"""
Test script to verify MCP agent setup and demonstrate usage.

This script verifies:
1. Agent module loads correctly
2. MCP configuration is parsed properly
3. Commands are generated correctly for each configuration
"""
import json
import sys
from pathlib import Path

# Add current directory to path
sys.path.insert(0, str(Path(__file__).parent))

# Now we need to be in harbor's Python environment
try:
    from mini_swe_agent_mcp import MiniSweAgentMCP
    print("✅ Successfully imported MiniSweAgentMCP")
except ImportError as e:
    print(f"❌ Failed to import: {e}")
    print("\nTo run this test:")
    print("  cd ~/harbor && uv run python /Users/sjarmak/code-intel-digest/test_mcp_setup.py")
    sys.exit(1)

def test_baseline_agent():
    """Test baseline agent (no MCP)."""
    print("\n" + "="*60)
    print("TEST 1: Baseline Agent (No MCP)")
    print("="*60)

    agent = MiniSweAgentMCP(
        logs_dir=Path("/tmp/test-logs/baseline"),
        model_name="anthropic/claude-sonnet-4",
    )

    print(f"Agent name: {agent.name()}")
    print(f"MCP servers configured: {agent.mcp_servers}")
    print(f"✅ Baseline agent created successfully (no MCP servers)")

    # Check what commands would be generated
    commands = agent.create_run_agent_commands("Fix the bug in calculator.py")
    print(f"\nNumber of commands: {len(commands)}")
    for i, cmd in enumerate(commands):
        print(f"\nCommand {i+1}:")
        print(f"  {cmd.command[:100]}...")

    return agent

def test_sourcegraph_mcp_agent():
    """Test agent with Sourcegraph MCP."""
    print("\n" + "="*60)
    print("TEST 2: Sourcegraph MCP Agent")
    print("="*60)

    mcp_config = {
        "sourcegraph": {
            "command": "npx",
            "args": ["-y", "@sourcegraph/cody-context-filters-mcp"],
            "env": {
                "SRC_ENDPOINT": "https://sourcegraph.com",
                "SRC_ACCESS_TOKEN": "fake_token_for_test"
            }
        }
    }

    agent = MiniSweAgentMCP(
        logs_dir=Path("/tmp/test-logs/sourcegraph"),
        model_name="anthropic/claude-sonnet-4",
        mcp_servers=mcp_config
    )

    print(f"Agent name: {agent.name()}")
    print(f"MCP servers configured: {list(agent.mcp_servers.keys())}")
    print(f"✅ Sourcegraph MCP agent created successfully")

    # Check MCP config generation
    mcp_config_output = agent._create_mcp_config_file(Path("/tmp/mcp_config.json"))
    print(f"\nMCP config would be written with command:")
    print(f"  {mcp_config_output[:150]}...")

    # Check what commands would be generated
    commands = agent.create_run_agent_commands("Search the codebase for similar bugs")
    print(f"\nNumber of commands: {len(commands)}")
    for i, cmd in enumerate(commands):
        print(f"\nCommand {i+1}:")
        print(f"  {cmd.command[:150]}...")

    return agent

def test_deepsearch_mcp_agent():
    """Test agent with Deep Search MCP."""
    print("\n" + "="*60)
    print("TEST 3: Deep Search MCP Agent")
    print("="*60)

    mcp_config = {
        "deepsearch": {
            "command": "uvx",
            "args": ["mcp-server-fetch"]
        }
    }

    agent = MiniSweAgentMCP(
        logs_dir=Path("/tmp/test-logs/deepsearch"),
        model_name="anthropic/claude-sonnet-4",
        mcp_servers=mcp_config
    )

    print(f"Agent name: {agent.name()}")
    print(f"MCP servers configured: {list(agent.mcp_servers.keys())}")
    print(f"✅ Deep Search MCP agent created successfully")

    # Check what commands would be generated
    commands = agent.create_run_agent_commands("Find documentation about this error")
    print(f"\nNumber of commands: {len(commands)}")
    for i, cmd in enumerate(commands):
        print(f"\nCommand {i+1}:")
        print(f"  {cmd.command[:150]}...")

    return agent

def test_json_parsing():
    """Test that JSON string parsing works (for CLI usage)."""
    print("\n" + "="*60)
    print("TEST 4: JSON String Parsing (CLI Simulation)")
    print("="*60)

    json_string = '{"sourcegraph":{"command":"npx","args":["-y","@sourcegraph/cody"]}}'

    agent = MiniSweAgentMCP(
        logs_dir=Path("/tmp/test-logs/json-test"),
        model_name="anthropic/claude-sonnet-4",
        mcp_servers=json_string  # Pass as string like CLI would
    )

    print(f"Input: {json_string}")
    print(f"Parsed MCP servers: {agent.mcp_servers}")
    print(f"✅ JSON parsing works correctly")

    return agent

def compare_configurations():
    """Compare the three configurations side by side."""
    print("\n" + "="*60)
    print("COMPARISON: Commands Generated by Each Configuration")
    print("="*60)

    configs = {
        "Baseline (No MCP)": {},
        "Sourcegraph MCP": {
            "sourcegraph": {
                "command": "npx",
                "args": ["-y", "@sourcegraph/cody-context-filters-mcp"]
            }
        },
        "Deep Search MCP": {
            "deepsearch": {
                "command": "uvx",
                "args": ["mcp-server-fetch"]
            }
        }
    }

    for name, mcp_config in configs.items():
        print(f"\n{name}:")
        print("-" * 40)
        agent = MiniSweAgentMCP(
            logs_dir=Path(f"/tmp/test-logs/{name.replace(' ', '-').lower()}"),
            model_name="anthropic/claude-sonnet-4",
            mcp_servers=mcp_config
        )
        commands = agent.create_run_agent_commands("Fix the bug")
        print(f"  Commands generated: {len(commands)}")
        print(f"  MCP servers: {list(mcp_config.keys()) if mcp_config else 'None'}")

def main():
    """Run all tests."""
    print("\n" + "="*60)
    print("MCP AGENT SETUP VERIFICATION")
    print("="*60)

    try:
        test_baseline_agent()
        test_sourcegraph_mcp_agent()
        test_deepsearch_mcp_agent()
        test_json_parsing()
        compare_configurations()

        print("\n" + "="*60)
        print("✅ ALL TESTS PASSED!")
        print("="*60)

        print("\nNext steps:")
        print("1. Run actual trials with harbor:")
        print("   harbor trials start --agent-import-path mini_swe_agent_mcp:MiniSweAgentMCP ...")
        print("\n2. Check MCP_ABLATION_SETUP.md for full usage examples")
        print("\n3. Verify MCP servers are installed:")
        print("   - Sourcegraph: npx -y @sourcegraph/cody-context-filters-mcp")
        print("   - Deep Search: uvx mcp-server-fetch")

    except Exception as e:
        print(f"\n❌ TEST FAILED: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()
