#!/usr/bin/env python3
"""
Combine SWE-bench repos with existing repo list, remove duplicates, and format.
"""

from datasets import load_dataset

# Existing repos from user's list
existing_repos = [
    "AbsInt/CompCert",
    "amazon-science/esci-data",
    "amusecode/amuse",
    "Anurag461/lm-evaluation-harness",
    "apache/airflow",
    "apache/flink",
    "apache/spark",
    "astropy/astropy",
    "bottlepy/bottle",
    "boostorg/boost",
    "BVLC/caffe",
    "ChaoningZhang/MobileSAM",
    "containerd/containerd",
    "danini/magsac",
    "django/django",
    "embeddings-benchmark/mteb",
    "embeddings-benchmark/results",
    "envoyproxy/envoy",
    "etcd-io/etcd",
    "facebook/react",
    "facebookresearch/fastText",
    "facebookresearch/hydra",
    "FFmpeg/FFmpeg",
    "fsspec/filesystem_spec",
    "gcc-mirror/gcc",
    "georgkrause/langcodes",
    "grpc/grpc",
    "hashicorp/consul",
    "hashicorp/vault",
    "jeffreywpli/test-secret-removal",
    "jcmgray/quimb",
    "klee/klee",
    "kubernetes/kubernetes",
    "keycloak/keycloak",
    "laude-institute/harbor",
    "LeelaChessZero/lc0",
    "linux/torvalds",
    "llvm/llvm-project",
    "LostCityRS/Server",
    "microsoft/vscode",
    "moby/moby",
    "mongodb/mongo",
    "nodejs/node",
    "numpy/numpy",
    "opencv/opencv",
    "openai/spinningup",
    "openai/whisper",
    "openwall/john",
    "ozkl/doomgeneric",
    "pallets/flask",
    "pandas-dev/pandas",
    "prometheus/prometheus",
    "protocolbuffers/protobuf",
    "psf/requests",
    "pytorch/pytorch",
    "sadiqj/ocaml",
    "scikit-learn/scikit-learn",
    "sjarmak/amp-sales-workbench",
    "sjarmak/CodeContextBench",
    "sjarmak/demo-bazel-monorepo",
    "sjarmak/TTX-dotnet",
    "SPOCKnots/pyknotid",
    "stan-dev/httpstan",
    "stp/stp",
    "tensorflow/tensorflow",
    "TheMikeMerrill/personal-site",
    "tiangolo/fastapi",
    "requests/requests",
    "psf/requests",
    "pallets/flask",
    "django/django",
    "tornadoweb/tornado",
    "aio-libs/aiohttp",
    "httplib2/httplib2",
    "grpc/grpc",
    "encode/httpx",
    "sethmlarson/urllib3",
    "facelessuser/wcwidth",
    "certifi/python-certifi",
    "pyca/cryptography",
    "psf/cpython",
    "numpy/numpy",
    "pandas-dev/pandas",
    "scikit-learn/scikit-learn",
    "scipy/scipy",
    "matplotlib/matplotlib",
    "pytorch/pytorch",
    "tensorflow/tensorflow",
    "keras-team/keras",
    "huggingface/transformers",
    "openai/openai-python",
    "anthropics/anthropic-sdk-python",
    "langchain-ai/langchain",
    "chroma-core/chroma",
    "vllm-project/vllm",
    "yarolegovich/DiscreteScrollView",
    "mathertel/DmxSerial2",
    "SaoYan/DnCNN-PyTorch",
    "thunlp/DocRED",
    "Ocramius/DoctrineBatchUtils",
    "simoninns/DomesdayDuplicator",
    "bigbaldy1128/DotNetDetour",
    "DotRas/DotRas",
    "Astronaut00/DoubleDataPointer",
    "tsung-wei-huang/DtCraft",
    "JeremyLikness/DurableDungeon",
    "piotrstenke/Durian",
    "ronellsicat/DxR",
    "MenghaoGuo/EANet",
    "violetprotocol/ERC1238-token",
    "pkerspe/ESP-FlexyStepper",
    "SpacehuhnTech/esp8266_deauther",
    "google-gemini/gemini-cli",
    "mansk1es/GhostFart",
    "31/GodotOnReady",
    "fritzem/Google-Dino-GBA",
    "KSemenenko/GoogleAnalyticsForXamarinForms",
    "JetBrains/Grammar-Kit",
    "graphql-python/graphene",
    "zhongzhuoyao/HCCR-GoogLeNet",
    "amitburst/HackerNews",
    "dzuelke/HadooPHP",
    "MarkPThomas/HeadFirst-OOAD",
    "royshil/HeadPosePnP",
    "Sapd/HeadsetControl",
    "puikinsh/Unite-Theme",
    "GlaireDaggers/Unity-Netcode.IO",
    "Real-Serious-Games/Unity-Weld",
    "bshishov/UnityTerrainErosionGPU",
    "ThaDafinser/UserAgentParser",
    "jhewlett/ValueObject",
    "Azure/Vector-Search-AI-Assistant",
    "sekkit/Verse.NET",
    "hitherejoe/Vineyard",
    "securifybv/Visual-Studio-BOF-template",
    "yixia/VitamioBundleStudio",
    "ViveSoftware/ViveMediaDecoder",
    "g0tmi1k/VulnInjector",
    "MengRao/WFMPMC",
    "Paving-Base/WSA-Tools",
    "944095635/WallpaperMaker",
    "FigBug/Wavetable",
    "laksan1/WebView2Example",
    "codesandbox/codesandbox-client",
    "hongwenjun/WinKcp_Launcher",
    "HyperSine/Windows10-CustomKernelSigners",
    "WiringProject/Wiring",
    "EngineHub/WorldGuard",
    "HighgoSoftware/XLogMiner",
    "Joel2B/XVideos-PornHub-RedTube-API",
    "OliveTreeBible/Xamarin.Transitions",
    "OAID/YSQfastfd",
    "dennislwy/YahooFinanceAPI",
    "roddone/YeelightAPI",
    "stephanstapel/ZUGFeRD-csharp",
    "ammarahm-ed/drawing-board",
    "stevearc/dressing.nvim",
    "aimagelab/dress-code",
    "simolus3/drift",
    "xerpi/ds3vita",
    "kevinsea/dsc-generator",
    "ArekSredzki/dstar-lite",
    "welai/dual-range-bar",
    "bradfrost/dumb-react",
    "zoogie/dumpTool",
    "mrexodia/dumpulator",
    "LukeSmithxyz/dwm",
    "mihirlad55/dwm-ipc",
    "nubot-nudt/dynamic_task_allocation",
    "neoighodaro-articles/e-commerce-laravel-vue",
    "Simpleyyt/eReading",
    "mapbox/earcut.hpp",
    "j-easy/easy-flows",
    "codewithsadee/anon-ecommerce-website",
    "EcsRx/ecsrx.roguelike2d",
    "NVlabs/edm2",
    "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
    "Blealtan/efficient-kan",
    "ekknod/efi-monitor",
    "electricui/electricui-embedded",
    "bradstewart/electron-boilerplate-vue",
    "hackergrrl/electron-speech",
    "elevate/elevate.metabase.tools",
    "zielmicha/emacs-android",
    "neo22s/emailvalidator",
    "kas-gui/kas",
    "andrew-schofield/keepass2-haveibeenpwned",
    "guelfoweb/knock",
    "jimmywangheng/knowledge_representation_pytorch",
    "dozoisch/koa-react-full-example",
    "rvboris/koa-useragent",
    "kokkos/kokkos-tutorials",
    "KDE/krusader",
    "Alban-Boissard/kwin-effects-blur-respect-rounded-decorations",
    "yznts/kyoto",
    "ant-design/ant-design-landing",
    "Edujugon/laradoo",
    "nyancodeid/laravel-8-stisla-jetstream",
    "mschwarzmueller/laravel-basics-youtube",
    "jacurtis/laravel-blog-tutorial",
    "staudenmeir/laravel-cte",
    "msurguy/laravel-facebook-login",
    "JasonMortonNZ/laravel-grunt",
    "stevebauman/laravel-husk",
    "bhaidar/laravel-kanban",
    "staudenmeir/laravel-merged-relations",
    "BKWLD/laravel-pug",
    "ralphjsmit/laravel-seo",
    "mschwarzmueller/laravel-shopping-cart-tutorial",
    "teepluss/laravel-theme",
    "PHPJunior/laravel-video-chat",
    "herusdianto/laravel-vue-crud",
    "kyleferguson/laravel-with-docker-example",
    "google-research/lasertagger",
    "goldsborough/latexpp",
    "reactor/reactor",
    "mihaip/readerisdead",
    "aidenybai/reaict",
    "no5ix/realtime-server-ue4-demo",
    "ros-controls/realtime_tools",
    "Enselic/recordmydesktop",
    "JS-Challenges/recursion-prompts",
    "puzzlerush/reddit-clone",
    "guanchuwang/redis-bench",
    "urbantrout/refactor-css",
    "relay-tools/relay-subscriptions",
    "borzunov/remoteink",
    "thlorenz/replpad",
    "NirDiamant/agents-towards-production",
    "flatiron/resourceful",
    "tableau/rest-api-samples",
    "mwaskom/seaborn",
    "pallets/flask",
    "psf/requests",
    "pydata/xarray",
    "pylint-dev/pylint",
    "pytest-dev/pytest",
    "scikit-learn/scikit-learn",
    "sphinx-doc/sphinx",
    "sympy/sympy",
    "dstndstn/xlsx2csv",
    "marmelab/react-admin",
    "chayxana/Restaurant-App",
    "cj0x39e/retrying-dynamic-import",
    "uutils/coreutils",
    "ayende/rhino-security",
    "fwkz/riposte",
    "QuokkaLight/rkduck",
    "HadoopIt/rnn-nlu",
    "humanmade/roles-to-taxonomy",
    "poliva/rootadb",
    "alsora/ros2-ORB_SLAM2",
    "DLu/roscompile",
    "open-compass/DevEval",
    "pavelrevak/rt_soldering_pen",
    "xiewei-wayne/rtmp-video-player-for-ios",
    "sjarmak/kubernetes-stripped",
    "sjarmak/CodeContextBench",
    "sjarmak/code-intelligence-digest",
]

def get_swebench_repos():
    """Extract repos from both SWE-bench datasets."""
    print("Loading SWE-bench Pro dataset...", flush=True)
    ds_pro = load_dataset("ScaleAI/SWE-bench_Pro", split="test")
    pro_repos = set(ex["repo"] for ex in ds_pro)

    print("Loading SWE-bench Verified dataset...", flush=True)
    ds_verified = load_dataset("princeton-nlp/SWE-bench_Verified", split="test")
    verified_repos = set(ex["repo"] for ex in ds_verified)

    return pro_repos | verified_repos

def main():
    # Get SWE-bench repos
    swebench_repos = get_swebench_repos()

    # Combine all repos
    all_repos = set(existing_repos) | swebench_repos

    # Sort alphabetically
    sorted_repos = sorted(all_repos)

    # Print in exact format requested
    for repo in sorted_repos:
        print(f'"{repo}",')

    print(f"\n# Total: {len(sorted_repos)} unique repositories", flush=True)
    print(f"# Added {len(swebench_repos - set(existing_repos))} new repos from SWE-bench", flush=True)

if __name__ == "__main__":
    main()
