"""
Cost Analysis View - GUI-driven cost and efficiency analysis.

Displays:
- Experiment selector and baseline agent configuration in sidebar
- Token costs (input/output), execution cost per agent
- Cost breakdown charts (Plotly bar charts)
- Cost regressions detection table
- CSV export
"""

import streamlit as st

from dashboard.components.breadcrumb import render_breadcrumb_navigation
from dashboard.utils.cost_config import (
    render_cost_config,
    run_and_display_cost,
    _render_cost_results,
)
from dashboard.utils.navigation import NavigationContext


def show_cost_analysis():
    """Display GUI-driven cost analysis view."""

    # Initialize navigation context if not present
    if "nav_context" not in st.session_state:
        st.session_state.nav_context = NavigationContext()

    nav_context = st.session_state.nav_context

    # Render breadcrumb navigation
    render_breadcrumb_navigation(nav_context)

    st.title("Cost Analysis")
    st.markdown("**Configure and run cost analysis from the GUI**")
    st.markdown("---")

    # Initialize loader from session state
    loader = st.session_state.get("analysis_loader")
    if loader is None:
        st.error("Analysis loader not initialized. Please visit Analysis Hub first.")
        return

    # Sidebar configuration
    with st.sidebar:
        config = render_cost_config(loader)

    if config is None:
        st.info("Select an experiment and baseline agent in the sidebar to begin.")
        return

    # Update navigation context
    nav_context.navigate_to("analysis_cost", experiment=config.experiment_id)

    # Run Analysis button
    run_clicked = st.button(
        "Run Cost Analysis",
        type="primary",
        use_container_width=True,
        key="cost_run_analysis",
    )

    st.markdown("---")

    if run_clicked:
        run_and_display_cost(loader, config)
    elif "cost_config_results" in st.session_state:
        # Re-render cached results if available
        import pandas as pd

        cached_df = st.session_state.get("cost_config_results")
        regression_df = st.session_state.get("cost_config_regression_results", pd.DataFrame())
        cost_result = st.session_state.get("cost_config_cost_result")
        if isinstance(cached_df, pd.DataFrame) and not cached_df.empty and cost_result is not None:
            _render_cost_results(cached_df, regression_df, cost_result, config)
        else:
            st.info("Click **Run Cost Analysis** to analyze costs with the current configuration.")
    else:
        st.info("Click **Run Cost Analysis** to analyze costs with the current configuration.")

    # Interpretation guide
    st.markdown("---")

    with st.expander("Cost Analysis Guide"):
        st.markdown("""
### Metrics

- **Total Cost (USD)**: Sum of all API calls for this agent across all tasks
- **Input Cost**: Cost of tokens sent to the model (prompt + context)
- **Output Cost**: Cost of tokens generated by the model (response)
- **Cost per Success**: Average cost per successful task completion
- **Cost Rank**: Agent ranking by total cost (1 = cheapest)
- **Efficiency Rank**: Agent ranking by pass rate per dollar (1 = most efficient)

### Cost Regressions

A cost regression is detected when a variant agent has:
- >10% increase in total cost vs baseline
- >10% increase in cost per success vs baseline
- Token increase without pass rate improvement

Severity levels: **Critical** (>30% increase), **High** (10-30%), **Medium** (tokens up, pass rate same/worse)
        """)
